BookStore.WebUI/Controllers/AdminController.cs
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        private IProductRepository _repository;
        public AdminController(IProductRepository repo)
        {
            _repository = repo;
        }
        public ViewResult Index()
        {
            return View(_repository.Books);
        }

        [HttpGet]
        public ViewResult Edit(int bookID)
        {
            return View(_repository.Books.FirstOrDefault(p => p.BookID == bookID));
        }

        [HttpPost]
        public ActionResult Edit(Book prod, HttpPostedFileBase image)
        {
            if(ModelState.IsValid)
            {
                if (image != null)
                {
                    prod.ImageMimeType = image.ContentType;
                    prod.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(prod.ImageData, 0, image.ContentLength);
                }
                _repository.SaveProduct(prod);
                TempData["message"] = string.Format("{0} has been saved", prod.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(prod);
            }
        }
        
        [HttpGet]
        public ViewResult Create()
        {
            return View("Edit", new Book());
        }

        [HttpPost]
        public ActionResult Delete(int bookID)
        {
            Book deleteProduct = _repository.DeleteProduct(bookID);
            if(deleteProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deleteProduct.Name);
            }
            return RedirectToAction("Index");
        }


    }
}

BookStore.WebUI/Controllers/ProductController.cs
using BookStore.Domain.Abstract;
using System.Linq;
using System.Web.Mvc;
using BookStore.Domain.Entities;
using BookStore.WebUI.Model;
using System.Collections.Generic;

namespace BookStore.WebUI.Controllers
{
    [AllowAnonymous]
    public class ProductController : Controller
    {
        public int PageSize = 15;
        CategoryModel categoryDefaultModel = new CategoryModel();
        private IProductRepository _repository;
        public ProductController(IProductRepository productRepository)
        {
            _repository = productRepository;
            categoryDefaultModel.CategoryList = new List<Category>();
            categoryDefaultModel.CategoryList = BindCategory();
        }


        public ViewResult List(CategoryModel categoryModel, int page = 1)
        { 

            ProductsListViewModel model = GetProductListViewModel(categoryModel, page);

            return View(model);
        }

        public PartialViewResult Paging(CategoryModel categoryModel, int page = 1)
        {
            ProductsListViewModel model = GetProductListViewModel(categoryModel, page);

            return PartialView(model);
        }

        private List<int> GetPriceRange(string str)
        {
            var priceRange = str.Split(new char[] { ',' })
                    .Select(p => int.Parse(p)).ToList();

            ViewBag.CurrentRange = "[" + priceRange[0].ToString() + "," + priceRange[1].ToString() + "]";

            return priceRange;
        }

        private ProductsListViewModel GetProductListViewModel(CategoryModel categoryModel, int page)
        {
            decimal minPrice = 0;
            decimal maxPrice = 0;
            ViewBag.CurrentRange = "[0, 99]";

            if (categoryModel.RangeSlider != null)
            {
                var priceRange = GetPriceRange(categoryModel.RangeSlider);
                minPrice = priceRange[0];
                maxPrice = priceRange[1];
            }
            List<string> checkedCategory = GetCheckedCategory(categoryModel);

            var query = _repository.Books
                .Where(p => (checkedCategory.Contains(p.Category) || !checkedCategory.Any()));

            if (minPrice > 0)
            {
                query = query.Where(p => p.Price > minPrice);
            }

            if (maxPrice > 0)
            {
                query = query.Where(p => p.Price < maxPrice);
            }

            if (categoryModel.PageSizeSelected != 0)
            {
                PageSize = categoryModel.PageSizeSelected;
            }

            var querySort = query.OrderBy(p => p.Price);

            if (categoryModel.SortTypeSelected == "Дорогие")
            {
                querySort = query.OrderByDescending(p => p.Price);
            }

            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = querySort
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemPerPage = PageSize,
                    TotalItem = query.Count()
                },
                SortTypeList = new SelectList(new List<string>
                {
                    "Дешевые",
                    "Дорогие",
                }),
                CategoryModel = categoryModel,
                PageSizeList = new SelectList(new List<int>() {
                    15,
                    30,
                    45,
                })
            };
            return model;
        }

        [HttpGet]
        public FileContentResult GetImage(int bookID)
        {
            Book prod = _repository.Books.FirstOrDefault(p => p.BookID == bookID);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        private List<string> GetCheckedCategory(CategoryModel categoryModel)
        {

            CategoryModel result = categoryDefaultModel;
            if (categoryModel.CategoryList != null)
            {
                result = categoryModel;
            }
            return result.CategoryList
            .Where(p => p.CheckedStatus == true)
            .Select(p => p.CategoryName)
            .ToList();

        }

        public ActionResult FilterByCategory(CategoryModel model)
        {
            ViewBag.CurrentRange = "[0, 99]";
            if (model.CategoryList != null)
            {

                return PartialView(model);
            }
            return PartialView(categoryDefaultModel);
        }

        public List<Category> BindCategory()
        {
            List<Category> objcountry = new List<Category>();
            IEnumerable<string> categories = _repository.Books
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);

            foreach (var item in categories)
            {
                objcountry.Add(new Category { CategoryName = item });
            }

            return objcountry;
        }
    }
}

BookStore.WebUI/Views/Admin/Edit.cshtml
@model BookStore.Domain.Entities.Book

@{
    ViewBag.Title = "Admin: Edit " + Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit @Model.Name</h1>

@using (Html.BeginForm("Edit", "Admin",
            FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()
    @Html.LabelFor(b => b.Name)
    @Html.TextBoxFor(b => b.Name, new { @class = "form-control", required = "", autofocus = "" })
    @Html.LabelFor(b => b.Description)
    @Html.TextAreaFor(b => b.Description, new { @class = "form-control", required = "", autofocus = "" })
    @Html.LabelFor(b => b.Price)
    @Html.TextBoxFor(b => b.Price, new { @class = "form-control", required = "", autofocus = "" })
    @Html.LabelFor(b => b.Category)
    @Html.TextBoxFor(b => b.Category, new { @class = "form-control", required = "", autofocus = "" })
    @Html.HiddenFor(b => b.BookID)

    <div class="editor-label">Image</div>
    <div class="editor-field">
        @if (Model.ImageData == null)
        {
            @:None
        }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.BookID })" />
        }
        <div>
            Upload new image:
            <input type="file" name="Image" />
        </div>    
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
    @Html.ActionLink("Cancel and return to List", "Index")
}

  

BookStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<BookStore.Domain.Entities.Book>

@{
    ViewBag.Title = "Admin: All Books";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>All Books</h1>
<p>@Html.ActionLink("Go to home page", "List", "Product")</p>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Actions</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@item.BookID</td>
        <td>@Html.ActionLink(item.Name, "Edit",  new { item.BookID })</td>
        <td class="NumericCol">@item.Price.ToString("c")</td>
        <td>
            @using(Html.BeginForm("Delete", "Admin"))
            {
                @Html.Hidden("BookID", item.BookID)
                <input type="submit" value="Delete" />
            }
        </td>
    </tr>
}
</table>
<p>@Html.ActionLink("Add a new book", "Create")</p>
<p>@Html.ActionLink("Go to home page", "List", "Product")</p>